defmodule IChing.Seeds.Hexagrams do
  def hexagrams do
    [
      {
        1,
        63,
        "The Creative",
        "Qián",
        "乾",
      },
      {
        2,
        0,
        "The Receptive",
        "Kūn",
        "坤",
      },
      {
        3,
        34,
        "Difficulty at the Beginning",
        "Zhūn",
        "屯",
      },
      {
        4,
        17,
        "Youthful Folly",
        "Méng",
        "蒙",
      },
      {
        5,
        58,
        "Waiting (Nourishment)",
        "Xū",
        "需",
      },
      {
        6,
        23,
        "Conflict",
        "Sòng",
        "訟",
      },
      {
        7,
        16,
        "The Army",
        "Shī",
        "師",
      },
      {
        8,
        2,
        "Holding Together [Union]",
        "Bǐ",
        "比",
      },
      {
        9,
        59,
        "The Taming Power of the Small",
        "Xiǎo chù",
        "小畜",
      },
      {
        10,
        55,
        "Treading [Conduct]",
        "Lǚ",
        "履",
      },
      {
        11,
        56,
        "Peace",
        "Tài",
        "泰",
      },
      {
        12,
        7,
        "Standstill [Stagnation]",
        "Pǐ",
        "否",
      },
      {
        13,
        47,
        "Fellowship with Men",
        "Tóng rén",
        "同人",
      },
      {
        14,
        61,
        "Possession in Great Measure",
        "Dà yŏu",
        "大有",
      },
      {
        15,
        8,
        "Modesty",
        "Qiān",
        "謙",
      },
      {
        16,
        4,
        "Enthusiasm",
        "Yù",
        "豫",
      },
      {
        17,
        38,
        "Following",
        "Suí",
        "隨",
      },
      {
        18,
        25,
        "Work on What Has Been Spoiled [Decay]",
        "Gŭ",
        "蠱",
      },
      {
        19,
        48,
        "Approach",
        "Lín",
        "臨",
      },
      {
        20,
        3,
        "Contemplation (View)",
        "Guān",
        "觀",
      },
      {
        21,
        37,
        "Biting Through",
        "Shì hè",
        "噬嗑",
      },
      {
        22,
        41,
        "Grace",
        "Bì",
        "賁",
      },
      {
        23,
        1,
        "Splitting Apart",
        "Bō",
        "剝",
      },
      {
        24,
        32,
        "Return (The Turning Point)",
        "Fù",
        "復",
      },
      {
        25,
        39,
        "Innocence (The Unexpected)",
        "Wú wàng",
        "無妄",
      },
      {
        26,
        57,
        "The Taming Power of the Great",
        "Dà xù",
        "大畜",
      },
      {
        27,
        33,
        "The Corners of the Mouth (Providing Nourishment)",
        "Yí",
        "頤",
      },
      {
        28,
        30,
        "Preponderance of the Great",
        "Dà guò",
        "大過",
      },
      {
        29,
        18,
        "The Abysmal (Water)",
        "Kăn",
        "坎",
      },
      {
        30,
        45,
        "The Clinging Fire",
        "Lí",
        "離",
      },
      {
        31,
        14,
        "Influence (Wooing)",
        "Xián",
        "咸",
      },
      {
        32,
        28,
        "Duration",
        "Héng",
        "恆",
      },
      {
        33,
        15,
        "Retreat",
        "Dùn",
        "遯",
      },
      {
        34,
        60,
        "The Power of the Great",
        "Dà zhuàng",
        "大壯",
      },
      {
        35,
        5,
        "Progress",
        "Jìn",
        "晉",
      },
      {
        36,
        40,
        "Darkening of the Light",
        "Míng yí",
        "明夷",
      },
      {
        37,
        43,
        "The Family [The Clan]",
        "Jiā rén",
        "家人",
      },
      {
        38,
        53,
        "Opposition",
        "Kuí",
        "睽",
      },
      {
        39,
        10,
        "Obstruction",
        "Jiăn",
        "蹇",
      },
      {
        40,
        20,
        "Deliverance",
        "Xiè",
        "解",
      },
      {
        41,
        49,
        "Decrease",
        "Sŭn",
        "損",
      },
      {
        42,
        35,
        "Increase",
        "Yì",
        "益",
      },
      {
        43,
        62,
        "Break-through (Resoluteness)",
        "Kuài",
        "夬",
      },
      {
        44,
        31,
        "Coming to Meet",
        "Gòu",
        "姤",
      },
      {
        45,
        6,
        "Gathering Together [Massing]",
        "Cuì",
        "萃",
      },
      {
        46,
        24,
        "Pushing Upward",
        "Shēng",
        "升",
      },
      {
        47,
        22,
        "Oppression (Exhaustion)",
        "Kùn",
        "困",
      },
      {
        48,
        26,
        "The Well",
        "Jĭng",
        "井",
      },
      {
        49,
        46,
        "Revolution (Molting)",
        "Gé",
        "革",
      },
      {
        50,
        29,
        "The Caldron",
        "Dĭng",
        "鼎",
      },
      {
        51,
        36,
        "The Arousing (Shock Thunder)",
        "Zhèn",
        "震",
      },
      {
        52,
        9,
        "Keeping Still Mountain",
        "Gèn",
        "艮",
      },
      {
        53,
        11,
        "Development (Gradual Progress)",
        "Jiàn",
        "漸",
      },
      {
        54,
        52,
        "The Marrying Maiden",
        "Guī mèi",
        "歸妹",
      },
      {
        55,
        44,
        "Abundance [Fullness]",
        "Fēng",
        "豐",
      },
      {
        56,
        13,
        "The Wanderer",
        "Lǚ",
        "旅",
      },
      {
        57,
        27,
        "The Gentle (The Penetrating Wind)",
        "Sùn",
        "巽",
      },
      {
        58,
        54,
        "The Joyous Lake",
        "Duì",
        "兌",
      },
      {
        59,
        19,
        "Dispersion [Dissolution]",
        "Huàn",
        "渙",
      },
      {
        60,
        50,
        "Limitation",
        "Jié",
        "節",
      },
      {
        61,
        51,
        "Inner Truth",
        "Zhōng fú",
        "中孚",
      },
      {
        62,
        12,
        "Preponderance of the Small",
        "Xiăo guò",
        "小過",
      },
      {
        63,
        42,
        "After Completion",
        "Jì jì",
        "既濟",
      },
      {
        64,
        21,
        "Before Completion",
        "Wèi jì",
        "未濟",
      }
    ]
  end
end
