defmodule IChing.Seeds.Images do
  def images do
    [
      "The movement of heaven is full of power.\nThus the superior man makes himself strong and untiring.",
      "The earth's condition is receptive devotion.\nThus the superior man who has breadth of character\nCarries the outer world.",
      "Clouds and thunder:\nThe image of DIFFICULTY AT THE BEGINNING.\nThus the superior man\nBrings order out of confusion.",
      "A spring wells up at the foot of the mountain:\nThe image of YOUTH.\nThus the superior man fosters his character\nBy thoroughness in all that he does.",
      "Clouds rise up to heaven:\nThe image of WAITING.\nThus the superior man eats and drinks,\nIs joyous and of good cheer.",
      "Heaven and water go their opposite ways:\nThe image of CONFLICT.\nThus in all his transactions the superior man\nCarefully considers the beginning.",
      "In the middle of the earth is water:\nThe image of THE ARMY.\nThus the superior man increases his masses\nBy generosity toward the people.",
      "On the earth is water:\nThe image of HOLDING TOGETHER.\nThus the kings of antiquity\nBestowed the different states as fiefs\nAnd cultivated friendly relations\nWith the feudal lords.",
      "The wind drives across heaven:\nThe image of THE TAMING POWER OF THE SMALL.\nThus the superior man\nRefines the outward aspect of his nature.",
      "Heaven above, the lake below:\nThe image of TREADING.\nThus the superior man discriminates between high and low,\nAnd thereby fortifies the thinking of the people.",
      "Heaven and earth unite: the image of PEACE.\nThus the ruler\nDivides and completes the course of heaven and earth;\nHe furthers and regulates the gifts of heaven and earth,\nAnd so aids the people.",
      "Heaven and earth do not unite:\nThe image of STANDSTILL.\nThus the superior man falls back upon his inner worth\nIn order to escape the difficulties.\nHe does not permit himself to be honored with revenue.",
      "Heaven togethr with fire:\nThe image of FELLOWSHIP WITH MEN.\nThus the superior man organizes the clans\nAnd makes distinctions between things.",
      "Fire in heaven above:\nThe image of POSSESSION IN GREAT MEASURE.\nThus the superior man curbs evil and furthers good,\nAnd thereby obeys the benevolent will of heaven.",
      "Within the earth, a mountain:\nThe image of MODESTY.\nThus the superior man reduces that which is too much,\nAnd augments that which is too little.\nHe weighs things and makes them equal.",
      "Thunder comes resounding out of the earth:\nThe image of ENTHUSIASM.\nThus the ancient kings made music\nIn order to honor merit,\nAnd offered it with splendor\nTo the Supreme Deity,\nInviting their ancestors to be present.",
      "Thunder in the middle of the lake:\nThe image of FOLLOWING.\nThus the superior man at nightfall\nGoes indoors for the rest and recuperation.",
      "The wind blows low on the mountain:\nThe image of DECAY.\nThus the superior man stirs up the people\nAnd strengthens their spirit.",
      "The earth above the lake:\nThe image of APPROACH.\nThus the superior man is inexhaustible\nIn his will to teach,\nAnd without limits\nIn his tolerance and protection of the people.",
      "The wind blows over the earth:\nThe image of CONTEMPLATION.\nThus the kings of old visited the regions of the world,\nContemplated the people,\nAnd gave them instruction.",
      "Thunder and lightning:\nThe image of BITING THROUGH.\nThus the kings of former times made firm the laws\nThrough clearly defined penalties.",
      "Fire at the foot of the mountain:\nThe image of GRACE.\nThus does the superior man proceed\nWhen clearing up current affairs.\nBut he dare not decide controversial issues in this way.",
      "The mountain rests on the earth:\nThe image of SPLITTING APART.\nThus those above can ensure their position\nOnly by giving generously to those below.",
      "Thunder within the earth:\nThe image of THE TURNING POINT.\nThus the kings of antiquity closed the passes\nAt the time of solstice.\nMerchants and strangers did not go about,\nAnd the ruler\nDid not travel through the provinces.",
      "Under heaven thunder rolls:\nAll things attain the natural state of innocence.\nThus the kings of old,\nRich in virtue, and in harmony with the time,\nFostered and nourished all beings.",
      "Heaven within the mountain:\nThe image of THE TAMING POWER OF THE GREAT.\nThus the superior man acquaints himself with many sayings of antiquity\nAnd many deeds of the past,\nIn order to strengthen his character thereby.",
      "At the foot of the mountain, thunder:\nThe image of PROVIDING NOURISHMENT.\nThus the superior man is careful of his words\nAnd temperate in eating and drinking.",
      "The lake rises above the trees:\nThe image of PREPONDERANCE OF THE GREAT.\nThus the superior man, when he stands alone,\nIs unconcerned,\nAnd if he has to renounce the world,\nHe is undaunted.",
      "Water flows on uninterruptedly and reaches its goal:\nThe image of the Abysmal repeated.\nThus the superior man walks in lasting virtue\nAnd carries on the business of teaching.",
      "That which is bright rises twice:\nThe image of FIRE.\nThus the great man, by perpetuating this brightness,\nIllumines the four quarters of the world.",
      "A lake on the mountain:\nThe image of influence.\nThus the superior man encourages people to approach him\nBy his readiness to receive them.",
      "Thunder and wind: the image of DURATION.\nThus the superior man stands firm\nAnd does not change his direction.",
      "Mountain under heaven: the image of RETREAT.\nThus the superior man keeps the inferior man at a distance,\nNot angrily but with reserve.",
      "Thunder in heaven above:\nThe image of THE POWER OF THE GREAT.\nThus the superior man does not tread upon paths\nThat do not accord with established order.",
      "The sun rises over the earth:\nThe image of PROGRESS.\nThus the superior man himself\nBrightens his bright virtue.",
      "The light has sunk into the earth:\nThe image of DARKENING THE LIGHT.\nThus does the superior man live with the great mass:\nHe veils his light, yet still shines.",
      "Wind comes forth from fire:\nThe image of THE FAMILY.\nThus the superior man has substance in his words\nAnd duration in his way of life.",
      "Above, fire; below, the lake:\nThe image of OPPOSITION.\nThus amid all fellowship\nThe superior man retains his individuality.",
      "Water on the mountain:\nThe image of OBSTRUCTION.\nThus the superior man turns his attention to himself\nAnd molds his character.",
      "Thunder and rain set in:\nThe image of DELIVERANCE.\nThus the superior man pardons mistakes\nAnd forgives misdeeds.",
      "At the foot of the mountain, the lake:\nThe image of DECREASE.\nThus the superior man controls his anger\nAnd restrains his instincts.",
      "Wind and thunder: the image of INCREASE.\nThus the superior man:\nIf he sees good, he imitates it;\nIf he has faults, he rids himself of them.",
      "The lake has risen up to heaven:\nThe image of BREAK-THROUGH.\nThus the superior man\nDispenses riches downward\nAnd refrains from resting on his virture.",
      "Under heaven, wind:\nThe image of COMING TO MEET.\nThus does the prince act when disseminating his commands\nAnd proclaiming them to the four quarters of heaven.",
      "Over the earth, the lake:\nThe image of GATHERING TOGETHER.\nThus the superior man renews his weapons\nIn order to meet the unforeseen.",
      "Within the earth, wood grows:\nThe image of PUSHING UPWARD.\nThus the superior man of devoted character\nHeaps up small things\nIn order to achieve something high and great.",
      "There is no water in the lake:\nThe image of EXHAUSTION.\nThus the superior man stakes his life\nOn following his will.",
      "Water over wood: the image of THE WELL.\nThus the superior man encourages the people at their work,\nAnd exhorts them to help one another.",
      "Fire in the lake: the image of REVOLUTION.\nThus the superior man\nSets the calendar in order\nAnd makes the seasons clear.",
      "Fire over wood:\nThe image of THE CALDRON.\nThus the superior man consolidates his fate\nBy making his position correct.",
      "Thunder repeated: the image of SHOCK.\nThus in fear and trembling\nThe superior man sets his life in order\nAnd examines himself.",
      "Mountains standing close together:\nThe image of KEEPING STILL.\nThus the superior man\nDoes not permit his thoughts\nTo go beyond his situation.",
      "On the mountain, a tree:\nThe image of DEVELOPMENT.\nThus the superior man abides in dignity and virtue,\nIn order to improve the mores.",
      "Thunder over the lake:\nThe image of THE MARRYING MAIDEN.\nThus the superior man\nUnderstands the transitory\nIn the light of the eternity of the end.",
      "Both thunder and lightning come:\nThe image of ABUNDANCE.\nThus the superior man decides lawsuits\nAnd carries out punishments.",
      "Fire on the mountain:\nThe image of THE WANDERER.\n Thus the superior man\nIs clear-minded and cautious\nIn imposing penalties,\nAnd protracts no lawsuits.",
      "Winds following one upon the other:\nThe image of THE GENTLY PENETRATING.\nThus the superior man\nSpreads his commands abroad\nAnd carries out his undertakings.",
      "Lakes resting one on the other:\nThe image of THE JOYOUS.\nThus the superior mans joins with his friends\nFor discussion and practice.",
      "The wind drives over the water:\nThe image of DISPERSION.\nThus the kings of old sacrificed to the Lord\nAnd built temples.",
      "Water over lake: the image of LIMITATION.\nThus the superior man\nCreates number and measure,\nAnd examines the nature of virtue and correct conduct.",
      "Wind over lake: the image of INNER TRUTH.\nThus the superior man discusses criminal cases\nIn order to delay executions.",
      "Thunder on the mountain:\nThe image of PREPONDERANCE OF THE SMALL.\nThus in his conduct the superior man gives preponderance to reverence.\nIn bereavement he gives preponderance to grief.\nIn his expenditures he gives preponderance to thrift.",
      "Water over fire: the image of the condition\nIn AFTER COMPLETION.\nThus the superior man\nTakes thought of misfortune\nAnd arms himself against it in advance.",
      "Fire over water:\nThe image of the condition before transition.\nThus the superior man is careful\nIn the differentiation of things,\nSo that each finds its place."
    ]
  end
end
