defmodule IChing.Seeds.Judgements do
  def judgements do
    [
      "THE CREATIVE works sublime success,\nFurthering through perseverance.",
      "THE RECEPTIVE brings about sublime success,\nFurthering through the perseverance of a mare.\nIf the superior man undertakes something and tries to lead,\nHe goes astray;\nBut if he follows, he finds guidance.\nIt is favorable to find friends in the west and south,\nTo forego friends in the east and north.\nQuiet perseverance brings good fortune.",
      "DIFFICULTY AT THE BEGINNING works supreme success,\nFurthering through perseverance.\nNothing should be undertaken.\nIt furthers one to appoint helpers.",
      "YOUTHFUL FOLLY has success.\nIt is not I who seek the young fool;\nThe young fool seeks me.\nAt the first oracle I inform him.\nIf he asks two or three times, it is importunity.\nIf he importunes, I give him no information.\nPerseverance furthers.",
      "WAITING. If you are sincere,\nYou have light and success.\nPerseverance brings good fortune.\nIt furthers one to cross the great water.",
      "CONFLICT. You are sincere\nAnd are being obstructed.\nA cautious halt halfway brings good fortune.\nGoing through to the end brings misfortune.\nIt furthers one to see the great man.\nIt does not further one to cross the great water.",
      "THE ARMY. The army needs perseverance\nAnd a strong man.\nGood fortune without blame.",
      "HOLDING TOGETHER brings good fortune.\nInquire of the oracle once again\nWhether you possess sublimity, constancy, and perseverance;\nThen there is no blame.\nThose who are uncertain gradually join.\nWhoever comes too late\nMeets with misfortune.",
      "THE TAMING POWER OF THE SMALL\nHas success.\nDense clouds, no rain from our western region.",
      "TREADING. Treading upon the tail of the tiger.\nIt does not bite the man. Success.",
      "PEACE. The small departs,\nThe great approaches.\nGood fortune. Success.",
      "STANDSTILL. Evil people do not further\nThe perseverance of the superior man.\nThe great departs; the small approaches.",
      "FELLOWSHIP WITH MEN in the open.\nSuccess.\nIt furthers one to cross the great water.\nThe perseverance of the superior man furthers.",
      "POSSESSION IN GREAT MEASURE.\nSupreme success.",
      "MODESTY creates success.\nThe superior man carries things through.",
      "ENTHUSIASM. It furthers one to install helpers\nAnd to set armies marching.",
      "FOLLOWING has supreme success.\nPerseverance furthers. No blame.",
      "WORK ON WHAT HAS BEEN SPOILED\nHas supreme success.\nIt furthers one to cross the great water.\nBefore the starting point, three days.\nAfter the starting point, three days.",
      "APPROACH has supreme success.\nPerseverance furthers.\nWhen the eighth month comes,\nThere will be misfortune.",
      "CONTEMPLATION. The ablution has been made,\nBut not yet the offering.\nFull of trust they look up to him.",
      "BITING THROUGH has success.\nIt is favorable to let justice be administered.",
      "GRACE has success.\nIN small matters\nIt is favorable to undertake something.",
      "SPLITTING APART. It does nto further one\nTo go anywhere.",
      "RETURN. Success.\nGoing out and coming in without error.\nFriends come without blame.\nTo and fro goes the way.\nOn the seventh day comes return.\nIt furthers one to have somewhere to go.",
      "INNOCENCE. Supreme success.\nPerseverance furthers.\nIf someone is not as he should be,\nHe has misfortune,\nAnd it does not further him\nTo undertake anything.",
      "THE TAMING POWER OF THE GREAT.\nPerseverance furthers.\nNot eating at home brings good fortune.\nIt furthers one to cross the great water.",
      "THE CORNERS OF THE MOUTH.\nPerseverance brings good fortune.\nPay heed to the providing of nourishment\nAnd to what a man seeks\nTo fill his own mouth with.",
      "PREPONDERANCE OF THE GREAT.\nThe ridgepole sags to the breaking point.\nIt furthers one to have to somewhere to go.\nSuccess.",
      "THE ABYSMAL repeated.\nIf you are sincere, you have success in your heart,\nAnd whatever you do succeeds.",
      "THE CLINGING. Perseverance furthers.\nIt brings success.\nCare of the cow brings good fortune.",
      "INFLUENCE. Success.\nPerseverance furthers.\nTo take a maiden to wife brings good fortune.",
      "DURATION. Success. No blame.\nPerseverance furthers.\nIt furthers one to have somewhere to go.",
      "RETREAT. Success.\nIn what is small, perseverance furthers.",
      "THE POWER OF THE GREAT. Perseverance furthers.",
      "PROGRESS. The powerful prince\nIs honored with horses in large numbers.\nIn a single day he is granted audience three times.",
      "DARKENING OF THE LIGHT. In adversity\nIt furthers one to be persevering.",
      "THE FAMILY. The perseverance of the woman furthers.",
      "OPPOSITION. In small matters, good fortune.",
      "OBSTRUCTION. The southwest furthers.\nThe northeast does not further.\nIt furthers one to see the great man.\nPerseverance brings good fortune.",
      "DELIVERANCE. The southwest furthers.\nIf there is no longer anything where one has to go,\nReturn brings good fortune.\nIf there is still something where one has to go,\nHastening brings good fortune.",
      "DECREASE combined with sincerity\nBrings about supreme good fortune\nWithout blame.\nOne may be persevering in this.\nIt furthers one to undertake something.\nHow is this to be carried out?\nOne may use two small bowls for the sacrifice.",
      "INCREASE. It furthers one\nTo undertake something.\nIt furthers one to cross the great water.",
      "BREAK-THROUGH. One must resolutely make the matter known\nAt the court of the king.\nIt must be announced truthfully. Danger.\nIt is necessary to notify one's own city.\nIt does not further to resort to arms.\nIt furthers one to undertake something.",
      "COMING TO MEET. The maiden is powerful.\nOne should not marry such a maiden.",
      "GATHERING TOGETHER. Success.\nThe king approaches his temple.\nIt furthers one to see the great man.\nThis brings success. Perseverance furthers.\nTo bring great offerings creates good fortune.\nIt furthers one to undertake something.",
      "PUSHING UPWARD has supreme success.\nOne must see the great man.\nFear not.\nDeparture toward the south\nBrings good fortune.",
      "OPPRESSION. Success. Perseverance.\nThe great man brings about good fortune.\nNo blame.\nWhen one has something to say,\nIt is not believed.",
      "THE WELL. The town may be changed,\nBut the well cannot be changed.\nIt neither decreases nor increases.\nThey come and go and draw from the well.\nIf one gets down almost to the water\nAnd the rope does not go all the way,\nOr the jug breaks, it brings misfortune.",
      "REVOLUTION. On your own day\nYou are believed.\nSupreme success,\nFurthering through perseverance.\nRemorse disappears.",
      "THE CALDRON. Supreme good fortune.\nSuccess.",
      "SHOCK brings success.\nShock comes-oh, oh!\nLaughing words-ha, ha!\nThe shock terrifies for a hundred miles,\nAnd he does not let fall the sacrificial spoon and chalice.",
      "KEEPING STILL. Keeping his back still\nSo that he no longer feels his body.\nHe goes into the courtyard\nAnd does not see his people.\nNo blame.",
      "DEVELOPMENT. The maiden\nIs given in marriage.\nGood fortune.\nPerseverance furthers.",
      "THE MARRYING MAIDEN.\nUndertakings bring misfortune.\nNothing that would further.",
      "ABUNDANCE has success.\nThe king attains abundance.\nBe not sad.\nBe like the sun at midday.",
      "THE WANDERER. Success through smallness.\nPerseverance brings good fortune\nTo the wanderer.",
      "THE GENTLE. Success through what is small.\nIt furthers one to have somewhere to go.\nIt furthers one to see the great man.",
      "THE JOYOUS. Success.\nPerseverance is favorable.",
      "DISPERSION. Success.\nThe king approaches his temple.\nIt furthers one to cross the great water.\nPerseverance furthers.",
      "LIMITATION. Success.\nGalling limitation must not be persevered in.",
      "INNER TRUTH. Pigs and fishes.\nGood fortune.\nIt furthers one to cross the great water.\nPerseverance furthers.",
      "PREPONDERANCE OF THE SMALL. Success.\nPerseverance furthers.\nSmall things may be done; great things should not be done.\nThe flying bird brings the message:\nIt is not well to strive upward,\nIt is well to remain below.\nGreat good fortune.",
      "AFTER COMPLETION. Success in small matters.\nPerseverance furthers.\nAt the beginning good fortune,\nAt the end disorder.",
      "BEFORE COMPLETION. Success.\nBut if the little fox, after nearly completing the crossing,\nGets his tail in the water,\nThere is nothing that would further."
    ]
  end
end
